CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR NOT NULL,
	joined DATE NOT NULL DEFAULT CURRENT_DATE,
	password_hash VARCHAR NOT NULL,
	salt VARCHAR NOT NULL,
	extra_rounds SMALLINT NOT NULL DEFAULT 0
)
