FROM scratch

ADD target/x86_64-unknown-linux-musl/release/server /ganbare/server
ADD static /ganbare/static
VOLUME /ganbare/audio /ganbare/images
ENV GANBARE_DATABASE_URL=postgres://drasa@172.17.0.2/ganbare_testing
ENV GANBARE_RUNTIME_PEPPER=4Y23isyrgd9ML/jJonemXNL0PnbMyerqnejHPBnDLaY=
ENV GANBARE_SERVER_BINDING=0.0.0.0:8080
ENV GANBARE_SITE_DOMAIN=localhost
ENV GANBARE_EMAIL_DOMAIN=akusento.ganba.re
WORKDIR /ganbare
EXPOSE 8080
ENTRYPOINT ["/ganbare/server"]
