version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: scripts/Dockerfile
      args:
        PROJECT_ROOT: '5KV6gxzAhAGRH1FfWaoPbg==' # Any base64 value will do
    image: golddranks/ganbare_web:tag
    ports:
      - "8080:8080"
  db:
    build:
      context: .
      dockerfile: scripts/Dockerfile.database
    image: golddranks/ganbare_database:tag
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
