ALTER TABLE events DROP COLUMN required_group;
ALTER TABLE events DROP COLUMN priority;
DELETE FROM event_experiences WHERE event_id=(SELECT id FROM events WHERE name='sorting_ceremony');
DELETE FROM event_experiences WHERE event_id=(SELECT id FROM events WHERE name='pretest');
DELETE FROM event_experiences WHERE event_id=(SELECT id FROM events WHERE name='posttest');
DELETE FROM event_userdata WHERE event_id=(SELECT id FROM events WHERE name='pretest');
DELETE FROM event_userdata WHERE event_id=(SELECT id FROM events WHERE name='posttest');
DELETE FROM events WHERE name='sorting_ceremony';
DELETE FROM events WHERE name='pretest';
DELETE FROM events WHERE name='posttest';
ALTER TABLE narrators DROP COLUMN published;
DELETE FROM group_memberships WHERE group_id=(SELECT id FROM user_groups WHERE group_name='ready_for_sorting');
DELETE FROM group_memberships WHERE group_id=(SELECT id FROM user_groups WHERE group_name='japani1');
DELETE FROM group_memberships WHERE group_id=(SELECT id FROM user_groups WHERE group_name='japani2');
DELETE FROM group_memberships WHERE group_id=(SELECT id FROM user_groups WHERE group_name='japani3');
DELETE FROM group_memberships WHERE group_id=(SELECT id FROM user_groups WHERE group_name='japani4');
DELETE FROM user_groups WHERE group_name='ready_for_sorting';
DELETE FROM user_groups WHERE group_name='japani1';
DELETE FROM user_groups WHERE group_name='japani2';
DELETE FROM user_groups WHERE group_name='japani3';
DELETE FROM user_groups WHERE group_name='japani4';
