DROP TABLE user_metrics;
DROP TABLE q_answer_data;
DROP TABLE e_answer_data;
DROP TABLE question_data;
DROP TABLE exercise_data;
DROP TABLE word_data;
DROP TABLE skill_data;
DROP TABLE event_experiences;
DROP TABLE due_items;
